spring:
  application:
    name: bnbserv
    
  ##### DB setting for mysql #####
  datasource:
    url: jdbc:mysql://HOST/DB_NAME
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 
    password: 
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect 
    hibernate:
      ddl-auto: update
    show-sql: true
  # sql:
  #   init:
  #     schema-locations: classpath:sql/schema.sql
  #     data-locations: classpath:sql/data.sql
  #     mode: always
  ####################

server:
  port: 8080